export interface PrivilegeModel {
  name: string
}

export enum PrivilegeEnum {
  CREATE_STUDENT = 'CREATE_STUDENT',
  CREATE_ACADEMIC_YEAR = 'CREATE_ACADEMIC_YEAR',
  CREATE_SUBJECT = 'CREATE_SUBJECT',
  CREATE_CLASSES = 'CREATE_CLASSES',
  CREATE_COURSE = 'CREATE_COURSE',
  CREATE_LECTURER = 'CREATE_LECTURER',
  READ_STUDENTS_LISTS = 'READ_STUDENTS_LISTS',
  READ_CLASSES_LISTS = 'READ_CLASSES_LISTS'
}
